import type { Metadata } from "next";
import "./globals.css";
import ProvidersClient from '../src/providers/ProvidersClient';
import Header from '../src/components/layout/Header';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ProvidersClient>
          <Header />
          {children}
        </ProvidersClient>
      </body>
    </html>
  );
}
